CREATE OR REPLACE VIEW ALL_WORKERS AS 
          SELECT last_name,first_name,age,FIRST_DAY AS "START_DATE", LAST_DAY  FROM WORKERS_FACTORY_1 wf WHERE LAST_DAY IS NULL  
          UNION 
          SELECT last_name, first_name,NULL,START_DATE, END_DATE AS "LAST_DAY" FROM WORKERS_FACTORY_2 wf  
          ORDER BY START_DATE DESC  WITH READ ONLY;
SELECT * FROM All_WORKERS;


CREATE OR REPLACE VIEW ALL_WORKERS_ELAPSED AS
SELECT TRUNC(CURRENT_DATE - start_date) AS "ELAPSED_TIME" FROM
    all_workers;
SELECT * FROM all_workers_elapsed;
CREATE OR REPLACE VIEW BEST_SUPPLIERS AS 
       SELECT supplier_id,quantity FROM SUPPLIERS_BRING_TO_FACTORY_1 sbtf 
       UNION 
       SELECT supplier_id,quantity FROM SUPPLIERS_BRING_TO_FACTORY_2 sbtf 
       WHERE Quantity >= 1000 
       ORDER BY Quantity DESC;
SELECT * FROM BEST_SUPPLIERS;

CREATE OR REPLACE
            VIEW ROBOTS_FACTORIES AS
           SELECT DISTINCT 
               *
           FROM
                ROBOTS r 
           NATURAL JOIN 
                ROBOTS_FROM_FACTORY rff 
           NATURAL JOIN FACTORIES f;
SELECT * FROM ROBOTS_FACTORIES;